# This dockerfile was created for development & testing purposes, for APT-based distro.
#
# Build as:             docker build -f Dockerfile.loong64 -t pwndbg .
#
# For testing use:      docker run --rm -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined pwndbg bash
#
# For development, mount the directory so the host changes are reflected into container:
#   docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v `pwd`:/pwndbg pwndbg bash
#

ARG image=ghcr.io/loong64/debian:trixie
FROM --platform=linux/loong64 $image AS base

ENV LANG=en_US.utf8
ENV TZ=America/New_York
ENV PWNDBG_VENV_PATH=/venv
ENV UV_PROJECT_ENVIRONMENT=/venv
ENV UV_LINK_MODE=copy

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        locales vim && \
    localedef -i en_US -c -f UTF-8 en_US.UTF-8

# pip/python dependencies
RUN apt install -y git python3 python3-dev python3-venv patch libncurses-dev libssl-dev libffi-dev pkg-config cmake build-essential curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile=minimal -y && \
    for bin in $HOME/.cargo/bin/*; do [ -x "$bin" ] && ln -sf "$bin" /usr/local/bin/$(basename "$bin"); done

# Pwndbg tests dependencies
RUN apt install -y make pkg-config gcc musl-tools golang libc6-dev libc6-dbg
# TODO: jemalloc build

# Pwndbg runtime dependencies
RUN cd /tmp/ && curl https://ziglang.org/download/0.14.1/zig-loongarch64-linux-0.14.1.tar.xz --output /tmp/zig-loongarch64-linux-0.14.1.tar.xz && \
    tar -xf /tmp/zig-loongarch64-linux-0.14.1.tar.xz && \
    rm /tmp/zig-loongarch64-linux-0.14.1.tar.xz && \
    mkdir -p /opt && \
    mv /tmp/zig-loongarch64-linux-0.14.1 /opt/zig/ && \
    ln -s /opt/zig/zig /usr/local/bin/zig

# Installing uv
RUN python3 -m venv /venv && \
    . /venv/bin/activate && \
    pip install uv --extra-index-url https://mirrors.loong64.com/pypi/simple && \
    rm -rf ~/.cache/

WORKDIR /pwndbg
COPY ./uv.lock /pwndbg/
COPY ./pyproject.toml /pwndbg/
# pyproject.toml requires these files, pip install would fail
RUN touch README.md && mkdir pwndbg && touch pwndbg/empty.py

RUN . /venv/bin/activate && \
    uv sync --all-groups --all-extras && \
    rm -rf ~/.cargo/registry/ && \
    rm -rf ~/.cache/

RUN rm README.md && rm -rf pwndbg

FROM base AS full

COPY . /pwndbg/

ENV PATH="${PWNDBG_VENV_PATH}/bin:${PATH}"
